### PR TITLE
Fix broken symlinks

### PR DESCRIPTION
**Pull request by SmartFinn**
Fixed symlinks:

- ./actions/16/gradient.svg → color-gradient.svg
- ./actions/22/edit-find-project.svg → edit-find.svg
- ./actions/22/gnumeric-superscript.svg → format-text-superscript.svg
- ./actions/22/kdenlive-show-audio.svg → ../../status/16/audio-volume-high.svg
- ./actions/24/run-install.svg → run-build-install.svg
- ./actions/32/arrow-down.svg → go-down.svg
- ./apps/symbolic/.svg symlink removed because youtube-dl-gui-symbolic.svg already exists
- ./apps/symbolic/image-viewer/accessories-image-viewer-symbolic.svg → image-viewer-symbolic.svg
- ./apps/symbolic/image-viewer/eog-symbolic.svg → image-viewer-symbolic.svg
- ./apps/symbolic/image-viewer/eom-symbolic.svg → image-viewer-symbolic.svg
- ./apps/symbolic/image-viewer/viewnior-symbolic.svg → image-viewer-symbolic.svg
- ./apps/symbolic/monitor/org.gnome.Usage-symbolicsvg renamed to org.gnome.Usage-symbolic.svg → monitor-symbolic.svg
- ./places/scalable/folder-orange-finder.svg →  folder-orange-mac.svg
- ./places/scalable/folder-orange-saved-search.svg → folder-orange-search.svg
- ./places/scalable/folder-orange-windows.svg → folder-orange-wine.svg

Removed a few trash files:
- ./.directory
- ./apps/scalable/.directory

### CODE REVIEW

**Comment by gusbemacbe** [comment]
Thank you, @SmartFinn. I will credit you for author of extra fixes and extra icons fixing. And the` build_color_folders.sh`, is it better for this icon themes tan `papirus_folders`?

**Comment by gusbemacbe** [comment]
I did not know that. An interesting idea. This shell script is very good for changing automatically and quickly the colour of folders without needing to change the colour of icon by icon in a vector editor.

**Comment by gusbemacbe** [comment]
But is this shell script possible to create automatically with 3 colours (dark colour, light colour and opaque white colour of symbol?

**Comment by SmartFinn** [comment]
> But is this shell script possible to create automatically with 3 colours (dark colour, light colour and opaque white colour of symbol?

Sure, but in your case for changing the white color you have to specify color in rgb format in `build_color_folders.sh` script.

**Comment by gusbemacbe** [comment]
Ah, I will replace RGB for HEX. I created the icons with Gravit Designer. It exported, using RGB instead of HEX.

**Comment by SmartFinn** [comment]
I don't sure that you can use gradients with HEX colors.

**Comment by gusbemacbe** [comment]
Ah, the symbols (for example, application icon, as you see in the screenshot) do not have gradient. They only opaque. The gradient is in the opaque white shape behind another light orange shape, as you notice in the screenshot. 

screen shot 2018-09-01 at 01 46 18

**Comment by gusbemacbe** [comment]
screen shot 2018-09-01 at 01 48 41

**Comment by gusbemacbe** [comment]
The gradient opaque white shape does not need to be relaced. Only the dark and light orange shapes and the symbol colour are OK to be replaced.

**Comment by gusbemacbe** [comment]
I checked the codes in SVG languages, all the symbols are always rgb(255,255,255). I will replace it for HEX. 

` ` `xml
<path d="..." id="application" fill="rgb(255,255,255)" fill-opacity="0.62"/></g></svg>
` ` `

**Pull request merged**
